declare module '@env'{
export const GEMINI_API_KEY="AIzaSyAN_kwr3JTOIQsjvMzMa_Sow3qd0269F4Y";
export const SUPABASE_URL="https://vaxtgiedwxknhwsfanac.supabase.co";
export const SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZheHRnaWVkd3hrbmh3c2ZhbmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzQ2ODMsImV4cCI6MjA2Nzc1MDY4M30.t5yrW3Y8lzY6DRwlpTagDZA5XoGPoCiTzMJ7PxA4lzQ";
}